#  Kopiere den Inhalt in die Zwischenablage und füge diesen dann in ein File 
#  mit dem Namen: Beeceptor.http in VS Code ein

@url = https://cab8836c98d6451e0b00.free.beeceptor.com

### Als erstes erstellen wir ein paar neuen User

POST {{url}}/api/users
Content-Type: application/json

{
  "first_name": "Fabian",
  "last_name": "Graf",
  "age": 25,
  "is_active": true
}

### Dann rufen wir die erstellten User ab
GET {{url}}/api/users

# Wir merken uns die Id des ersten Users
@id = 01058bb06abc5d4a460d

### Get single user
GET {{url}}/api/users/{{id}}

### Get single user  (Not found)
GET {{url}}/api/users/64e234c636203e876d47d

### Update User mit PUT 
PUT {{url}}/api/users/{{id}}
Content-Type: application/json

{
  "first_name": "Fabian",
  "last_name": "Mustermann",
  "age": 40,
  "is_active": true
}

### Den veränderten Record abrufen
GET {{url}}/api/users/{{id}}


### Update user mit Patch
PATCH  {{url}}/api/users/{{id}}
Content-Type: application/json

{
  "is_active": false
}

### Den veränderten Record abrufen
GET {{url}}/api/users/{{id}}

### Delete todo (Bitte Id anpassen)
DELETE  {{url}}/api/users/{{id}}

### Versuch den gelöschen Record erneut zu lesen
GET {{url}}/api/users/{{id}}

